default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  username: postgres
  password: 12345678
  pool: 5

development:
  <<: *default
  database: rails-tutorial_development


test:
  <<: *default
  database: rails-tutorial_test
